### PR TITLE
Refactor repo to work in areaDetector 

### PR DESCRIPTION
**Pull request by stuwilkins**
@ulrikpedersen @MarkRivers This is the PR which converts the DLS specsAnalyser to a AD version which builds. It goes along with PR areaDetector/areaDetector#46

WIP at the moment, but will confirm later today if works at IOS. 

Thanks to all, this has been a big help at NSLS-II!

### CODE REVIEW

**Comment by stuwilkins** [comment]
@MarkRivers @ulrikpedersen This version is now tested at IOS and found to be working. There are a few changes in stuwilkins@06dc7ab05f5ae5e6195c1e57fbda487d2afbf311 and stuwilkins@ccfff07de2f625d25e768cf093abde45b62e4eb3 which I had to do to get the IOC to work on our system but I believe these should not change how it is used at DLS.

**Comment by ulrikpedersen** [comment]
The commits on #3 seems to include the same or similar changes...?

**Comment by stuwilkins** [comment]
Yes, #3 was an internal branch I was using to make changes to get it working at IOS. However as the changes were not specific I moved them to this refactor branch. I plan to keep open #3 for now as the staff have asked for some extra features. I am working on docs now and once this is merged I will open a PR for that!

**Comment by stuwilkins** [comment]
@ulrikpedersen this is the good branch

**Comment by stuwilkins** [comment]
Hi! From my side this is OK to merge as we have been using this at the IOS beamline with no issues. Can we merge this? Are these changes acceptable to the DLS team (@ulrikpedersen). 

Anything else that people would like to see?

**Pull request merged**
